version: '3'

services:

  mongodb:
    build: ./mongo
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    depends_on:
      - mongodb
    ports:
      - 3300:3000

  scrapy:
    build: ./scrapy
    container_name: scrapy
    depends_on:
      - mongodb
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: 12345
      MONGODB_DB: kinoprogramm
      MONGODB_COLLECTION:  kinos